#' Aggregate counts from multiple .h5 files generated by Cell Ranger
#' @param filenames Character vector with paths to 1 or more .h5 files
#' @param min_var Minimum number of non-zero variables (rows) per observation (column).
#' @param min_obs Minimum number of non-zero observations (columns) per variable (row).
read_h5_files <- function(filenames, min_var = 10, min_obs = NULL) {
  # filenames <- Sys.glob("analysis/terra/cellranger-per-channel/output/*/*.h5")
  my_counts_list <- pbapply::pblapply(filenames, function(my_h5_file) {
    my_barcodes <- rhdf5::h5read(my_h5_file, "matrix/barcodes")
    # This is hacky, may want to provide more flexibility
    my_channel <- basename(dirname(my_h5_file))
    my_barcodes <- sprintf("%s|%s", my_channel, my_barcodes)
    h5 <- rhdf5::h5read(my_h5_file, "matrix")
    counts <- Matrix::sparseMatrix(
      dims   = h5$shape,
      i      = as.numeric(h5$indices),
      p      = as.numeric(h5$indptr),
      x      = as.numeric(h5$data),
      index1 = FALSE
    )
    colnames(counts) <- my_barcodes
    rownames(counts) <- as.data.frame(h5[["features"]])$id
    return(counts[,Matrix::colSums(counts > 0) > min_var])
  })
  rhdf5::h5closeAll()
  # Make sure all the count matrices have the same number of rows
  stopifnot(length(unique(lapply(my_counts_list, nrow))) == 1)
  # A convoluted way to concatenate all the matrices.
  # ncols <- cumsum(sapply(my_counts_list, function(x) x@Dim[2]))
  # x <- data.table::rbindlist(lapply(seq_along(my_counts_list), function(i) {
  #   # summary() converts to triplets (i,j,x)
  #   x <- summary(my_counts_list[[i]])
  #   if (i > 1) {
  #     x$j <- x$j + ncols[i - 1]
  #   }
  #   return(x)
  # }))
  # counts <- Matrix::sparseMatrix(
  #   dims   = c(my_counts_list[[1]]@Dim[1], ncols[length(ncols)]),
  #   i      = x$i,
  #   j      = x$j,
  #   x      = x$x,
  #   index1 = TRUE
  # )
  # rm(x)
  counts <- do.call(cbind, my_counts_list)
  return(counts)
}

#' Aggregate counts from multiple .h5 files generated by Cell Ranger
#' @param filenames Character vector with paths to 1 or more .h5 files
read_h5_files2 <- function(filenames) {
  # filenames <- Sys.glob("analysis/terra/cellranger-per-channel/output/*/*.h5")
  xs <- pbapply::pblapply(filenames, function(my_h5_file) {
    my_barcodes <- rhdf5::h5read(my_h5_file, "matrix/barcodes")
    # This is hacky, may want to provide more flexibility
    my_channel <- basename(dirname(my_h5_file))
    my_barcodes <- sprintf("%s|%s", my_channel, my_barcodes)
    h5 <- rhdf5::h5read(my_h5_file, "matrix")
    h5$colnames <- my_barcodes
    h5$colindices <- rep(1:h5$shape[2], diff(h5$indptr)) - 1
    h5$rownames <- as.data.frame(h5[["features"]])$id
    return(h5)
  })
  # Make sure all the count matrices have the same genes
  nrows <- sapply(xs, function(x) length(x$rownames))
  stopifnot(length(unique(nrows)) == 1)
  offsets <- cumsum(sapply(xs, function(x) x$shape[2]))
  if (length(xs) > 1) {
    for (i in 2:length(xs)) {
      xs[[i]]$colindices <- xs[[i]]$colindices + offsets[i - 1]
    }
  }
  # lengths <- sapply(xs, function(x) length(x$data))
  # cum_lengths <- cumsum(lengths)
  # total_length <- sum(lengths)
  # i <- vector("integer", total_length)
  # j <- vector("integer", total_length)
  # x <- vector("integer", total_length)
  # for (k in seq_along(xs)) {
  #   if (k > 1) {
  #     ix <- (cum_lengths[k-1] + 1):cum_lengths[k]
  #   } else {
  #     ix <- 1:cum_lengths[k]
  #   }
  #   i[ix] <- xs[[k]]$indices
  #   j[ix] <- xs[[k]]$colindices
  #   x[ix] <- xs[[k]]$data
  # }
  d <- data.table::rbindlist(lapply(xs, function(x) {
    list(i = x$indices, j = x$colindices, x = x$data)
  }))
  res <- Matrix::sparseMatrix(i = d$i, j = d$j, x = d$x, index1 = FALSE)
  rownames(res) <- xs[[1]]$rownames
  colnames(res) <- unlist(lapply(xs, "[[", "colnames"))
  return(counts)
}
